<?php

class MappingShmSaver extends ShmBase implements iMappingSaver
{
    const SHMKEY = 5;

    public function __construct($server)
    {
        parent::__construct(self::SHMKEY);
    }

    public function write($data)
    {
        parent::write(json_encode($data)); // TODO: Change the autogenerated stub
    }

    public function read()
    {
        return json_decode(parent::read(), true); // TODO: Change the autogenerated stub
    }


}